### ISSUE TITLE
Shadow masks display incorrectly with PAL output

### ISSUE THREAD

**Issue by MilanPolle** [MiSTer-devel/ShadowMasks_MiSTer#32]
Noticed at first with the PSX core (WipEout 3 SE PAL, on the 60 to 50 Hz switch early on). Noticeable with most LamerDeluxe masks/nano/ masks, except aperture grille.

Good test patterns are SlotBright19 and CheckeredBright19.

Testing with NES (as it is not WIP like the PSX core):
Super Mario Bros. (Europe) (PAL-SM).nes
Though the game shouldn't matter.

Core set to NTSC (5x crop, integer scaling etc. don't seem to matter), boot the game from the core menu.
Notice the way the pattern looks.
Set core to PAL, reset the core to reboot the game.
Notice the pattern looks quite different. The pattern should look the same on NTSC and PAL.

See images (top one is PAL, bottom one NTSC, both using the SlotBright19 pattern):

![SuperMarioBrosPAL_SlotBright19](https://user-images.githubusercontent.com/12609997/146675241-47edbeda-ddfb-480a-84d8-29d7bcf044b0.jpg)
![SuperMarioBrosNTSC_SlotBright19](https://user-images.githubusercontent.com/12609997/146675249-3c8d0757-12c8-4a46-89f7-85a441a1e5e6.jpg)

**Comment by sorgelig** [comment]
i was testing SlotBright19 on NES with 240p Suite ROM. Switched between NTSC and PAL back and forth - didn't see difference. May be some games "play" with hsync and thus destroys the mask?
Do you use LCD or CRT display? May be it's specific to your display.

**Comment by MilanPolle** [comment]
Both these screenshots are on an LCD display. I have the same difference between PAL and NTSC on the PSX core.
I'll test with the 240p suite as well.

**Comment by sorgelig** [comment]
masks are applied on HDMI output resolution, so it doesn't matter which scaling is used or which filter is applied. It also doesn't matter which frame rate is used.
So i have no idea what's wrong with your case.. It seems your LCD display applies some filtering internally depending on 50/60 frame rate.

Many LCD displays internally have fixed 60Hz refresh rate, so when 50Hz video is supplied, Monitor/TV uses special tricks to smooth the frames to fit into 60Hz refresh. And your LCD it seems does this.

**Comment by MilanPolle** [comment]
Good point, I'll check that tomorrow. I just remembered my monitor/tv has horizontal and vertical sharpening settings per screen mode, it might be set wrong for PAL.

**Comment by MilanPolle** [comment]
It was indeed the horizontal and vertical sharpness settings of my monitor that hadn't been set correctly for the PAL screen mode. I adjusted it and now it looks correct. I'll let people on Discord know these settings can potentially make shadow masks look incorrect.

This issue can be closed, thanks for your quick help!
