### ISSUE TITLE
Feature Request: Start drawing Shadow Masks with game data.

### ISSUE THREAD

**Issue by tonurics** [MiSTer-devel/ShadowMasks_MiSTer#35]
There are Shadow Masks that rely on being aligned with the "pixels" they will modify for the correct effect. Masks currently appear to start with the screen, not with the "viewport" [game being drawn]. It would be very helpful for all Masks to start with the viewport instead.

If auto-magically detecting the viewport and drawing from there is prohibitively difficult: perhaps a set of x & y offsets can be added to the GUI instead.

Thanks.

Here's an example of where alignment is important and does not line up:
![wrong](https://user-images.githubusercontent.com/983921/147172441-97533cf1-43c9-4b1f-a7d3-fb9bf170b671.jpg)

**Comment by sorgelig** [comment]
which core is it?

**Comment by tonurics** [comment]
The image is from a Game Boy test core with Shadow Mask support that Soltan shared on discord [ https://discord.com/channels/647909397477195803/811089485495402497/923019813251600455 ]. I reported the issue to him first, but he said that it was likely a common issue on all cores.

> Soltan_G42, 2021-12-22 4:38PM
> "The shadowmask code starts drawing the masks as soon as vsync and hsync are off.  That means they probably are drawing over the whole hdmi res not just the game image. I say "probably" because sorgelig wrote the current code and it should be possible to start drawing somehow in the actual game image. I don't think he did that already though."
> https://discord.com/channels/647909397477195803/811089485495402497/923373993250132029

To which, I said: I would create this feature request about it.

**Comment by sorgelig** [comment]
vertical align should be easy while horizontal isn't as it uses pipeline

**Comment by sorgelig** [comment]
Basically it's already out of "shadow mask" definition. On CRT you cannot have perfect pixel alignment.
What you show is ugly hack of shadow mask to mimic LCD filter. You have to use specific resolution with specific scaling for specific core. Too much specifics. Don't tell me you are going to add 1000 new masks for all these variations. It's ugly hack as i've said and very inconvenient to use. It's not what shadowmask was made for. Use LCD scaling filter which is aligned to pixels and not depend on resolutions.

**Comment by tonurics** [comment]
Well from a certain point of view the whole filter is an ugly hack. :)

But to the point: everyone can use Mosaic [PenTile, MG Stripe, etc.] masks on their screens; they create the appearance of higher resolutions and more details, while having nothing to do with actual CRTs. Which is why Soltan's original concept cores contained multiple Mosaic masks and were quickly voted as the best options.

I have two 4K TVs at home; a LG and a Vizio. The LG works great. But the Vizio due to it's sub-pixel layout and odd scaling renders virtually every CRT filter unusable. So when I first started up the official release and couldn't find any of the formerly great looking Mosaic masks, I set about recreating them. And later: other Mosaic options when the scope of the sub-pixel layouts issue became apparent. We are often educating confused users on Discord about sub-pixel layouts after they have tried all the suggestions they saw elsewhere; and ultimately we point them to try Mosaic masks.

So from my perspective, going all the way back to the original concept: the "Shadow Masks" feature was never limited to recreating CRT effects. The name "Shadow Masks" was just convenient abet historical misnomer.

To speak directly to your concern about "1000 new masks for all these variations" I personally was planning on only targeting these LCD "Hack" masks to integer scaling at 720p, 1080p, and 1440p in handheld cores where this issue presented itself, the masks themselves are already finished [See Here](https://twitter.com/tonurics/status/1473812163454115840).

My feature request for an alignment solution is to avoid having a stupid number of offset variations addressing the end-user resolutions. Even if you can only give vertical align: that would cut down the number of offset variations by half; the number of offset variations would need to be based on the width of the mask. Although, at that point: I would hope that you would be open to having a end-user offset option on the GUI instead.

I should add that, when this came up yesterday: Soltan also spoke about creating masks himself that will need to be correctly aligned; but I don't know what his intentions are.

---

We haven't had a chance to fully discuss this. But some thought has been given to other improvements that touch upon this area, such as: including multiple mask resolutions within the same *.txt file. So the number of end user options are reduced and they automatically receive the version of the mask that best fits their screen. [Not really useful to the Mosaic masks; but to CRT and LCD "Hack" masks.]

**Comment by tonurics** [comment]
I suppose I should also say, in regards to scaling filters: it was my understanding that they are only able to "normal" blend  `f(a,b) = b` colours during interpolation steps. Not giving the finer colour control of the Shadow Masks filter. A side effect of that is the scaling filters don't adapt to colour changes and can appear blurry. [Feel free to correct me if I'm wrong. I mostly know the Shadow Mask side of the equation.]

Below is the LCD Scaling filter example from the official Wiki page, along side the new Shadow Masks mask I created:

![bitmap](https://user-images.githubusercontent.com/983921/147342729-14548391-a323-45f0-89a5-69e51c5d65c0.png)
 
That is a simple black and white example; where I knew of a side-by-side comparison that could be given [intended to highlight my understanding of how colours are blended with the Scaling filter]. In the colour LCD "Hack" masks I've created: I'm not using black or white, instead relying on colour to mimic the actual LCD sub-pixel layouts of the screens [The nyquist of red next to blue causes dark lines to appear]. So I would think the differences between the Scaling filters and Shadow Masks will only be greater in colour.

![download_7_foo](https://user-images.githubusercontent.com/983921/147344857-1e08c41a-8861-4083-bf00-2b5ed85e794a.png)

**Comment by sorgelig** [comment]
I will make alignment of mask

**Comment by tonurics** [comment]
You are a prince among men. I think the LCD "Hack" masks will make a lot of people happy, so on their behalf and mine: thank you for hearing me out and working on the feature.

**Comment by tonurics** [comment]
This request has been fulfilled.
