### ISSUE TITLE
Resolution color changing bug

### ISSUE THREAD

**Issue by trashuncle** [MiSTer-devel/ShadowMasks_MiSTer#51]
When using the resolution feature, it seems that when setting multiple resolutions, or possibly using the wrong? resolution (1080 with crop) you will get distorted colors.

I have included some sample files, so you can see what happens.  I tested in 1080p with 5x crop.

If you switch the mask files, you will see the color variations.

It is more obvious with the 5x_Trin sample, as its the exact same mask and only one mask included.

[5x_Trin_Bright_1200.txt](https://github.com/MiSTer-devel/ShadowMasks_MiSTer/files/7828873/5x_Trin_Bright_1200.txt)
[A Grille [Monochrome] 1200.txt](https://github.com/MiSTer-devel/ShadowMasks_MiSTer/files/7828874/A.Grille.Monochrome.1200.txt)
[A Grille [Monochrome] 1080.txt](https://github.com/MiSTer-devel/ShadowMasks_MiSTer/files/7828875/A.Grille.Monochrome.1080.txt)
[5x_Trin_Bright_1080.txt](https://github.com/MiSTer-devel/ShadowMasks_MiSTer/files/7828876/5x_Trin_Bright_1080.txt)

**Comment by sorgelig** [comment]
quick look revealed incorrect format.

"v2" is PER MASK (as per description in my example i gave you before).

it means:

```
resolution=XXX
v2
<mask>

resolution=YYY
v2
<mask>
```

if you omit v2 from specific mask then it will be parsed as v1 mask.

**Comment by trashuncle** [comment]
Ah, yes that makes sense.  thanks!
